### ISSUE TITLE
laravel-admin中，多应用其实是多了整个一组admin_user_相关的表。但dcat没有看到

### ISSUE THREAD

**Issue by neatstudio** [jqhwx/dcat-admin-comments#58]
目前只是说：参考：http://www.dcatadmin.com/docs/master/multi-app.html
```
自定义用户和权限可以参考以上更改菜单的方式。另外如果是自定义用户的话，还需要更改配置文件config/new-admin.php中的以下参数
```
并没有相应的用户权限相关，是否目前还不支持？或者只能手工处理？

**Comment by jqhph** [comment]
支持啊，你把`new-admin.php`中的权限表配置跟菜单一样都改了不就是独立的了？你有认真看独立菜单表配置的示例吗？

另外不要在这里提issue。

**Comment by neatstudio** [comment]
我知道你的意思，我本意是说在admin:app的时候。其实没有根据 新后台的名字自动生成migration。还是得自己处理一下。
